name: handyman_provider_flutter
description: A new Flutter project.
publish_to: 'none'
version: 11.13.2+94

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^7.1.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  html: ^0.15.5+1
  http: ^1.3.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_vector_icons: ^2.0.0
  path_provider: ^2.1.5
  dotted_border: ^2.1.0
#  custom_date_range_picker: ^1.1.0

  #Firebase
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.6
  firebase_pagination: ^4.1.0
  firebase_messaging: ^15.2.5

  flutter_local_notifications: ^19.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_custom_tabs: ^2.3.0
  syncfusion_flutter_charts: ^29.1.38
  geocoding: ^3.0.0
  webview_flutter: ^4.10.0
  country_picker: ^2.0.27

  #image:
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  file_picker: ^10.1.2
  lottie: ^3.3.1
  crop_image: ^1.0.16

  # PAYMENTS
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main  
  phonepe_payment_sdk: ^2.0.3
  flutter_stripe: ^11.5.0
  razorpay_flutter: ^1.4.0
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.1.0
      
  #IN APP PURCHASE
  purchases_flutter: ^8.7.2

  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
  custom_map_markers: ^0.0.2+1
  permission_handler: ^12.0.0+1
  share_plus: ^10.1.4


  async: any
  path: any
  uuid: any
  crypto: any
  permission_handler_platform_interface: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/